import json
import os

root = os.path.join(os.path.dirname(__file__), "..", "rules")
root = os.path.normpath(root)


def rule(
    rid,
    sev,
    contains,
    summary,
    why,
    look,
    recs,
    title=None,
    allc=None,
    tags=None,
):
    return {
        "id": rid,
        "severity": sev,
        "match_contains": contains,
        "match_all_contains": allc or [],
        "title": title or rid.split(".")[-1].replace("_", " ").title(),
        "summary": summary,
        "why": why,
        "whatToLookFor": look,
        "recommendation": recs if isinstance(recs, list) else [recs],
        "tags": tags or [],
    }


spring = [
    rule(
        "springboot.npe",
        "critical",
        ["NullPointerException", "Cannot invoke"],
        "La aplicación intentó usar un objeto vacío (null).",
        "Suele ser un fallo de código o de datos de entrada no validados.",
        ["NullPointerException", "Cannot invoke", "at com…"],
        [
            "Revisa el stacktrace (clase/método).",
            "Valida entradas nulas antes de usarlas.",
            "Vuelve a desplegar tras el fix.",
        ],
        title="NullPointerException",
        tags=["jvm"],
    ),
    rule(
        "springboot.oom",
        "critical",
        ["OutOfMemoryError", "Java heap space"],
        "El proceso Java se quedó sin memoria heap.",
        "Fugas, cargas grandes o heap demasiado pequeño.",
        ["OutOfMemoryError", "Java heap space"],
        ["Revisa uso de memoria del pod.", "Ajusta heap o reduce carga (fuera de Faro)."],
        title="OutOfMemoryError",
        tags=["jvm", "memory"],
    ),
    rule(
        "springboot.bean_creation",
        "critical",
        ["BeanCreationException"],
        "Falló la creación de un bean al arrancar o al inyectar dependencias.",
        "Config faltante, bean circular o dependencia no disponible.",
        ["BeanCreationException", "Error creating bean"],
        ["Lee la causa anidada (Caused by).", "Revisa properties/yamls del ConfigMap."],
        title="Fallo al crear bean",
        tags=["boot"],
    ),
    rule(
        "springboot.datasource",
        "critical",
        ["CannotGetJdbcConnectionException", "Failed to configure a DataSource"],
        "No se pudo obtener o configurar el DataSource JDBC.",
        "BD caída, red, credenciales o URL incorrecta.",
        ["CannotGetJdbcConnectionException", "DataSource"],
        ["Verifica conectividad a la BD desde el cluster.", "Confirma URL/usuario fuera de Faro."],
        title="DataSource / JDBC",
        tags=["db"],
    ),
    rule(
        "springboot.hikari",
        "critical",
        ["HikariPool", "Connection is not available"],
        "El pool Hikari no pudo entregar una conexión a tiempo.",
        "Pool agotado, queries lentas o BD saturada.",
        ["HikariPool", "Connection is not available"],
        ["Revisa tamaño del pool y queries lentas.", "Mira latencia hacia la BD."],
        title="Pool Hikari agotado",
        tags=["db"],
    ),
    rule(
        "springboot.sql",
        "critical",
        ["SQLException", "DataAccessException", "PSQLException"],
        "Error al hablar con la base de datos (SQL, conexión o mapeo).",
        "Consulta inválida, constraint, timeout o driver.",
        ["SQLException", "DataAccessException"],
        ["Lee el SQLException anidado.", "Verifica esquema y conectividad BD."],
        title="Error de acceso a datos",
        tags=["db"],
    ),
    rule(
        "springboot.security_denied",
        "warn",
        ["AccessDeniedException", "Access is denied"],
        "Un acceso fue denegado por Spring Security.",
        "Roles insuficientes o regla de autorización.",
        ["AccessDeniedException", "403"],
        ["Confirma roles del principal.", "Revisa reglas SecurityFilterChain."],
        title="Acceso denegado",
        tags=["auth"],
    ),
    rule(
        "springboot.unauthorized",
        "warn",
        ["AuthenticationException", "Unauthorized", "401"],
        "Fallo de autenticación o llamada no autorizada.",
        "Token/credencial inválida o ausente.",
        ["401", "Unauthorized", "AuthenticationException"],
        ["Verifica token/sesión del cliente.", "Revisa configuración OAuth/JWT fuera de Faro."],
        title="No autorizado",
        tags=["auth"],
    ),
    rule(
        "springboot.webclient",
        "warn",
        ["WebClientResponseException", "WebClientRequestException"],
        "Falló una llamada HTTP reactiva (WebClient).",
        "Downstream caído, timeout o 4xx/5xx.",
        ["WebClientResponseException", "WebClientRequestException"],
        ["Mira status y body de la respuesta.", "Revisa URL y timeouts del cliente."],
        title="WebClient falló",
        tags=["network"],
    ),
    rule(
        "springboot.feign",
        "warn",
        ["FeignException", "RetryableException"],
        "Falló un cliente Feign hacia otro servicio.",
        "Downstream, serialización o reintentos agotados.",
        ["FeignException", "RetryableException"],
        ["Identifica el servicio destino en el mensaje.", "Revisa circuit breaker / retries."],
        title="Cliente Feign",
        tags=["network"],
    ),
    rule(
        "springboot.timeout",
        "warn",
        ["SocketTimeoutException", "Read timed out", "TimeoutException", "Timeout", "timed out"],
        "Una llamada tardó demasiado y se canceló.",
        "Latencia de red o dependencia lenta.",
        ["timed out", "SocketTimeout", "TimeoutException"],
        ["Revisa latencia de dependencias.", "Ajusta timeouts con cuidado."],
        title="Timeout",
        tags=["network"],
    ),
    rule(
        "springboot.validation",
        "warn",
        ["MethodArgumentNotValidException", "ConstraintViolationException"],
        "Falló la validación de entrada (Bean Validation).",
        "Payload incompleto o inválido.",
        ["MethodArgumentNotValidException", "ConstraintViolation"],
        ["Revisa campos marcados en el error.", "Corrige el cliente o las anotaciones @Valid."],
        title="Validación de entrada",
        tags=["api"],
    ),
    rule(
        "springboot.bind",
        "warn",
        ["Failed to bind", "Failed to convert property"],
        "Falló el binding de propiedades de configuración.",
        "Tipo incorrecto o property faltante.",
        ["Failed to bind", "BindException"],
        ["Revisa application.yml / env vars.", "Compara tipos esperados vs valores."],
        title="Bind de configuración",
        tags=["boot"],
    ),
    rule(
        "springboot.kafka",
        "warn",
        ["KafkaException", "SerializationException", "CommitFailedException"],
        "Error en productor/consumidor Kafka.",
        "Broker, serialización o commit de offsets.",
        ["KafkaException", "SerializationException"],
        ["Revisa conectividad a brokers.", "Valida serializers y topic."],
        title="Error Kafka",
        tags=["messaging"],
    ),
    rule(
        "springboot.class_not_found",
        "critical",
        ["ClassNotFoundException", "NoClassDefFoundError"],
        "Falta una clase en el classpath en runtime.",
        "Dependencia no empaquetada o versión incompatible.",
        ["ClassNotFoundException", "NoClassDefFoundError"],
        ["Revisa el fat-jar / imagen.", "Alinea versiones de librerías."],
        title="Clase no encontrada",
        tags=["jvm"],
    ),
    rule(
        "springboot.illegal_state",
        "warn",
        ["IllegalStateException"],
        "El código entró en un estado ilegal.",
        "Secuencia de llamadas incorrecta o recurso cerrado.",
        ["IllegalStateException"],
        ["Lee el mensaje y el frame de aplicación.", "Revisa ciclo de vida del componente."],
        title="IllegalStateException",
        tags=["jvm"],
    ),
    rule(
        "springboot.rest_client",
        "warn",
        ["ResourceAccessException", "HttpServerErrorException", "HttpClientErrorException"],
        "Falló RestTemplate / HTTP client de Spring.",
        "4xx/5xx o error de E/S hacia downstream.",
        ["HttpServerErrorException", "HttpClientErrorException", "ResourceAccessException"],
        ["Mira el status HTTP.", "Verifica el servicio remoto."],
        title="Error HTTP cliente",
        tags=["network"],
    ),
    rule(
        "springboot.transaction",
        "warn",
        ["UnexpectedRollbackException", "TransactionSystemException"],
        "Falló o se revirtió una transacción.",
        "Excepción en el boundary @Transactional o recurso TX.",
        ["UnexpectedRollbackException", "TransactionSystemException"],
        ["Busca la causa raíz bajo Caused by.", "Revisa excepciones en el servicio."],
        title="Transacción fallida",
        tags=["db"],
    ),
    rule(
        "springboot.json",
        "warn",
        ["HttpMessageNotReadableException", "JsonParseException", "UnrecognizedPropertyException"],
        "No se pudo leer/escribir JSON del request/response.",
        "Payload malformado o propiedad desconocida.",
        ["HttpMessageNotReadableException", "JsonParseException"],
        ["Valida el body enviado por el cliente.", "Revisa DTOs Jackson."],
        title="JSON inválido",
        tags=["api"],
    ),
    rule(
        "springboot.multipart",
        "warn",
        ["MaxUploadSizeExceededException", "MultipartException"],
        "Falló la subida multipart (tamaño o parseo).",
        "Archivo demasiado grande o request corrupto.",
        ["MaxUploadSizeExceededException", "MultipartException"],
        ["Revisa límites spring.servlet.multipart.", "Pide al cliente un archivo menor."],
        title="Upload multipart",
        tags=["api"],
    ),
    rule(
        "springboot.circular",
        "critical",
        ["BeanCurrentlyInCreationException", "requested bean is currently in creation"],
        "Dependencia circular entre beans.",
        "Inyección mutua sin lazy/@Lazy.",
        ["BeanCurrentlyInCreationException"],
        ["Rompe el ciclo con @Lazy o rediseño.", "Revisa el grafo de beans en el mensaje."],
        title="Dependencia circular",
        tags=["boot"],
    ),
    rule(
        "springboot.port",
        "critical",
        ["Address already in use", "Port already in use"],
        "No se pudo bindear el puerto del servidor.",
        "Otro proceso usa el mismo puerto.",
        ["Address already in use", "Port already in use"],
        ["Cambia server.port o libera el puerto.", "En K8s revisa contenedores duplicados."],
        title="Puerto en uso",
        tags=["boot"],
    ),
    rule(
        "springboot.ssl",
        "warn",
        ["SSLHandshakeException", "PKIX path building failed"],
        "Falló el handshake TLS/SSL.",
        "Certificado no confiable o hostname mismatch.",
        ["SSLHandshakeException", "PKIX"],
        ["Revisa truststore/CA.", "No deshabilites TLS en producción."],
        title="TLS/SSL",
        tags=["network", "security"],
    ),
    rule(
        "springboot.reactor",
        "warn",
        ["Connection prematurely closed BEFORE response", "ReactorNetty"],
        "Error de red en stack Reactor Netty.",
        "Conexión cerrada por peer o idle timeout.",
        ["Connection prematurely closed", "ReactorNetty"],
        ["Revisa timeouts del cliente WebFlux.", "Verifica estabilidad del peer."],
        title="Reactor Netty",
        tags=["network"],
    ),
    rule(
        "springboot.oauth",
        "warn",
        ["AccessDenied", "OAuth2"],
        "Problema de acceso OAuth2 / denegación.",
        "Scopes o token inválido.",
        ["OAuth2", "AccessDenied"],
        ["Confirma scopes del cliente.", "Revisa authorization server."],
        title="OAuth2 / acceso",
        tags=["auth"],
    ),
    rule(
        "springboot.generic_error",
        "info",
        ["ERROR", "Exception", "EXCEPTION"],
        "Se registró un evento de error o excepción genérico.",
        "Puede ser síntoma; prioriza reglas específicas si también matchean.",
        ["ERROR", "Exception"],
        ["Lee el mensaje completo y el stack.", "Busca un Caused by más específico."],
        title="Error genérico",
        tags=["ops"],
    ),
]

liquibase = [
    rule(
        "liquibase.changelog_lock",
        "critical",
        ["Waiting for changelog lock", "Could not acquire change log lock", "LockException"],
        "Liquibase no pudo adquirir el lock del changelog.",
        "Otra instancia migra o quedó un lock huérfano tras un crash.",
        ["DATABASECHANGELOGLOCK", "Waiting for changelog lock", "Locked by"],
        [
            "Confirma que solo un Job/pod corre migrate.",
            "Si es lock huérfano, libéralo con ops/DBA fuera de Faro.",
        ],
        title="Changelog bloqueado",
        tags=["migration", "db"],
    ),
    rule(
        "liquibase.checksum",
        "critical",
        ["ValidationFailedException", "checksum validation failed", "checksums do not match"],
        "Falló la validación de checksums de Liquibase.",
        "Se editó un changeset ya aplicado o el historial no coincide.",
        ["checksum", "ValidationFailedException"],
        [
            "No edites changesets aplicados.",
            "Coordina clearChecksums solo con DBA/proceso aprobado.",
        ],
        title="Checksum inválido",
        tags=["migration"],
    ),
    rule(
        "liquibase.migration_failed",
        "critical",
        ["Migration Failed", "MigrationFailedException"],
        "Una migración Liquibase falló al ejecutarse.",
        "SQL inválido, permiso o estado inconsistente.",
        ["Migration Failed", "MigrationFailedException"],
        ["Lee el changeset que falló.", "Corrige el SQL y reintenta con proceso controlado."],
        title="Migración fallida",
        tags=["migration", "db"],
        allc=["liquibase"],
    ),
    rule(
        "liquibase.duplicate",
        "warn",
        ["DuplicateChangeSetException"],
        "Changeset duplicado o conflicto de id.",
        "Mismo id/author en más de un archivo.",
        ["DuplicateChangeSet"],
        ["Unifica ids de changesets.", "Revisa includes del master changelog."],
        title="Changeset duplicado",
        tags=["migration"],
    ),
    rule(
        "liquibase.db_exception",
        "critical",
        ["DatabaseException"],
        "Liquibase recibió un error de base de datos.",
        "Permisos, objeto faltante o SQL rechazado.",
        ["DatabaseException"],
        ["Lee el SQLException anidado.", "Verifica permisos del usuario de migrate."],
        title="DatabaseException Liquibase",
        tags=["db", "migration"],
        allc=["liquibase"],
    ),
    rule(
        "liquibase.lock_table",
        "warn",
        ["DATABASECHANGELOGLOCK"],
        "Aparece la tabla/señal DATABASECHANGELOGLOCK en el log.",
        "Indica contención o inspección del lock.",
        ["DATABASECHANGELOGLOCK"],
        ["Revisa quién tiene el lock (Locked by).", "Evita varios migrators concurrentes."],
        title="Señal DATABASECHANGELOGLOCK",
        tags=["migration"],
    ),
    rule(
        "liquibase.update_failed",
        "critical",
        ["UpdateFailedException", "update command failed"],
        "El comando update de Liquibase falló.",
        "Error durante apply de changesets.",
        ["UpdateFailedException"],
        ["Identifica el changeset fallido.", "Corrige y reintenta de forma controlada."],
        title="Update fallido",
        tags=["migration"],
    ),
    rule(
        "liquibase.precondition",
        "warn",
        ["PreconditionFailedException"],
        "Falló una precondición de changeset.",
        "El entorno no cumple lo que el changelog exige.",
        ["PreconditionFailedException"],
        ["Lee la precondición en el mensaje.", "Ajusta entorno o el changeset."],
        title="Precondición fallida",
        tags=["migration"],
    ),
    rule(
        "liquibase.rollback",
        "warn",
        ["RollbackFailedException", "rollback failed"],
        "Falló un rollback de Liquibase.",
        "Rollback incompleto o no soportado por el changeset.",
        ["RollbackFailedException"],
        ["Revisa scripts de rollback.", "Evalúa restore desde backup con ops."],
        title="Rollback fallido",
        tags=["migration"],
    ),
    rule(
        "liquibase.generic",
        "info",
        ["liquibase"],
        "Mensaje relacionado con Liquibase sin regla más específica.",
        "Puede ser informativo o síntoma parcial.",
        ["liquibase"],
        [
            "Busca excepciones Liquibase más arriba en el log.",
            "Prioriza lock/checksum/migration si aparecen.",
        ],
        title="Liquibase (genérico)",
        tags=["migration"],
    ),
]

nodejs = [
    rule(
        "nodejs.unhandled_rejection",
        "critical",
        ["UnhandledPromiseRejection", "unhandledRejection"],
        "Una promesa falló sin manejador.",
        "Falta catch/await try o listener de rechazo.",
        ["UnhandledPromiseRejection", "unhandledRejection"],
        [
            "Añade .catch o try/await.",
            "Registra process.on('unhandledRejection') para diagnosticar.",
        ],
        title="Promesa no manejada",
        tags=["node"],
    ),
    rule(
        "nodejs.typeerror",
        "critical",
        ["TypeError:"],
        "TypeError: valor con tipo incorrecto (null/undefined o API mal usada).",
        "Acceso a propiedad de undefined o argumentos inválidos.",
        ["TypeError:"],
        ["Revisa el frame at Object. / archivo.", "Valida argumentos antes de usarlos."],
        title="TypeError",
        tags=["node"],
    ),
    rule(
        "nodejs.reference",
        "critical",
        ["ReferenceError:"],
        "Se usó una variable no definida.",
        "Typo o import faltante.",
        ["ReferenceError:"],
        ["Busca el identificador en el mensaje.", "Revisa imports/scope."],
        title="ReferenceError",
        tags=["node"],
    ),
    rule(
        "nodejs.enoent",
        "warn",
        ["ENOENT", "no such file or directory"],
        "No se encontró un archivo o ruta.",
        "Path incorrecto o working directory distinto.",
        ["ENOENT"],
        ["Comprueba rutas de config/assets.", "Verifica cwd del proceso en el pod."],
        title="ENOENT",
        tags=["fs"],
    ),
    rule(
        "nodejs.econn",
        "warn",
        ["ECONNREFUSED", "ECONNRESET", "ETIMEDOUT"],
        "Falló una conexión de red.",
        "Servicio destino caído o no alcanzable.",
        ["ECONNREFUSED", "ECONNRESET", "ETIMEDOUT"],
        ["Verifica host/puerto del servicio.", "Revisa NetworkPolicy/DNS del cluster."],
        title="Error de conexión",
        tags=["network"],
    ),
    rule(
        "nodejs.eaddrinuse",
        "critical",
        ["EADDRINUSE"],
        "El puerto ya está en uso.",
        "Otro proceso escucha el mismo port.",
        ["EADDRINUSE"],
        ["Cambia PORT o evita réplicas chocando en hostNetwork."],
        title="Puerto en uso",
        tags=["node"],
    ),
    rule(
        "nodejs.syntax",
        "critical",
        ["SyntaxError:"],
        "Error de sintaxis en JS cargado en runtime.",
        "Archivo corrupto o transpile incompleto.",
        ["SyntaxError:"],
        ["Revisa el build/artifact.", "Confirma que el bundle es el esperado."],
        title="SyntaxError",
        tags=["node"],
    ),
    rule(
        "nodejs.express",
        "warn",
        ["Cannot GET", "Cannot POST"],
        "Error típico de ruta Express no encontrada.",
        "Ruta no registrada o method incorrecto.",
        ["Cannot GET", "Cannot POST"],
        ["Revisa definición de rutas.", "Confirma method y path."],
        title="Express routing",
        tags=["http"],
        allc=["express"],
    ),
    rule(
        "nodejs.nest",
        "warn",
        ["NestFactory", "ExceptionsHandler"],
        "Error reportado por NestJS.",
        "Excepción en handler o bootstrap.",
        ["NestFactory", "ExceptionsHandler"],
        ["Lee el exception filter output.", "Revisa el módulo/provider implicado."],
        title="NestJS",
        tags=["node"],
    ),
    rule(
        "nodejs.mongodb",
        "warn",
        ["MongoServerError", "MongoNetworkError"],
        "Error de cliente MongoDB.",
        "Auth, red o query inválida.",
        ["MongoServerError", "MongoNetworkError"],
        ["Verifica URI y red al cluster Mongo.", "Revisa auth fuera de Faro."],
        title="MongoDB",
        tags=["db"],
    ),
    rule(
        "nodejs.jwt",
        "warn",
        ["JsonWebTokenError", "TokenExpiredError"],
        "JWT inválido o expirado.",
        "Firma incorrecta o TTL vencido.",
        ["JsonWebTokenError", "TokenExpiredError"],
        ["Revisa secret/issuer.", "Pide al cliente renovar token."],
        title="JWT",
        tags=["auth"],
    ),
    rule(
        "nodejs.payload",
        "warn",
        ["PayloadTooLargeError"],
        "Body demasiado grande.",
        "Límite body-parser/express excedido.",
        ["PayloadTooLargeError"],
        ["Ajusta limit del parser.", "Reduce payload del cliente."],
        title="Payload grande",
        tags=["http"],
    ),
    rule(
        "nodejs.cors",
        "warn",
        ["Not allowed by CORS"],
        "Bloqueo CORS.",
        "Origen no permitido en el servidor.",
        ["Not allowed by CORS"],
        ["Ajusta Access-Control-Allow-Origin.", "Verifica preflight OPTIONS."],
        title="CORS",
        tags=["http"],
    ),
    rule(
        "nodejs.heap",
        "critical",
        ["JavaScript heap out of memory", "FATAL ERROR: Reached heap limit"],
        "Node se quedó sin heap.",
        "Memory leak o dataset grande.",
        ["heap out of memory", "Reached heap limit"],
        [
            "Revisa leaks.",
            "Ajusta NODE_OPTIONS --max-old-space-size con cuidado (fuera de Faro).",
        ],
        title="Heap OOM",
        tags=["memory"],
    ),
    rule(
        "nodejs.generic_error",
        "info",
        ["Error:", "ERROR"],
        "Error genérico en log Node.",
        "Puede ser síntoma; prioriza reglas específicas.",
        ["Error:"],
        ["Lee el stack completo.", "Busca códigos errno específicos."],
        title="Error genérico Node",
        tags=["ops"],
    ),
]

react = [
    rule(
        "react.chunk_load",
        "critical",
        ["ChunkLoadError", "Loading chunk"],
        "Falló la carga de un chunk JS del frontend.",
        "Deploy parcial, CDN o red; hash de chunk desactualizado.",
        ["ChunkLoadError", "Loading chunk"],
        [
            "Pide hard refresh al usuario.",
            "Verifica que todos los assets del release estén publicados.",
        ],
        title="ChunkLoadError",
        tags=["frontend"],
    ),
    rule(
        "react.hydration",
        "warn",
        ["Hydration failed", "Text content did not match", "Did not expect server HTML"],
        "Falló la hidratación React (SSR vs cliente).",
        "Markup distinto entre servidor y cliente.",
        ["Hydration failed", "did not match"],
        [
            "Busca HTML condicional por Date/random.",
            "Revisa suppressHydrationWarning solo si es consciente.",
        ],
        title="Hydration mismatch",
        tags=["frontend"],
    ),
    rule(
        "react.minified",
        "critical",
        ["Minified React error"],
        "Error React minificado en producción.",
        "Bug de render o hooks; el número apunta al decoder de React.",
        ["Minified React error"],
        [
            "Abre el decoder oficial con el # del error.",
            "Reproduce en build no minificado si puedes.",
        ],
        title="Minified React error",
        tags=["frontend"],
    ),
    rule(
        "react.invalid_hook",
        "critical",
        ["Invalid hook call", "Hooks can only be called"],
        "Uso inválido de Hooks.",
        "Duplicado de React o hook fuera de componente función.",
        ["Invalid hook call"],
        ["Asegura una sola copia de react.", "No llames hooks en condicionales."],
        title="Invalid hook call",
        tags=["frontend"],
    ),
    rule(
        "react.fetch_chunk",
        "warn",
        [
            "Failed to fetch dynamically imported module",
            "error loading dynamically imported module",
        ],
        "Falló un import() dinámico.",
        "Red o asset 404 tras deploy.",
        ["dynamically imported module"],
        ["Verifica URL del módulo.", "Revisa caché/CDN del release."],
        title="Dynamic import falló",
        tags=["frontend"],
    ),
    rule(
        "react.keys",
        "warn",
        ['unique "key" prop', "Each child in a list should have a unique"],
        "Faltan keys únicas en una lista.",
        "Rendimiento y bugs de reconciliación.",
        ["unique key"],
        ["Asigna key estable por ítem.", "Evita index como key si la lista muta."],
        title="Keys de lista",
        tags=["frontend"],
    ),
    rule(
        "react.dom",
        "warn",
        ["Target container is not a DOM element"],
        "React no encontró el contenedor DOM.",
        "root element ausente o mal id.",
        ["Target container is not a DOM element"],
        ["Verifica index.html #root.", "Confirma orden de scripts."],
        title="Contenedor DOM",
        tags=["frontend"],
    ),
    rule(
        "react.router",
        "warn",
        ["No routes matched location"],
        "Ruta no matcheada en React Router.",
        "Path incorrecto o basename.",
        ["No routes matched location"],
        ["Revisa definición de routes.", "Confirma basename del deploy."],
        title="Router sin match",
        tags=["frontend"],
    ),
    rule(
        "react.generic",
        "info",
        ["react-dom"],
        "Mensaje relacionado con React sin regla más específica.",
        "Puede ser warning informativo.",
        ["react-dom"],
        ["Busca ChunkLoad/Hydration/Minified si coexisten."],
        title="React (genérico)",
        tags=["frontend"],
    ),
]

python = [
    rule(
        "python.traceback",
        "critical",
        ["Traceback (most recent call last)"],
        "Hay un traceback de Python: una excepción no controlada llegó arriba.",
        "Bug, dependencia o config incorrecta.",
        ["Traceback (most recent call last)", 'File "'],
        ["Lee la última excepción del traceback.", "Abre el File/line indicado."],
        title="Traceback",
        tags=["python"],
    ),
    rule(
        "python.module_not_found",
        "critical",
        ["ModuleNotFoundError", "No module named"],
        "Falta un módulo Python en el entorno.",
        "Dependencia no instalada en la imagen o PYTHONPATH.",
        ["ModuleNotFoundError", "No module named"],
        ["Añade el paquete al requirements/image.", "Verifica el virtualenv del contenedor."],
        title="ModuleNotFoundError",
        tags=["python"],
    ),
    rule(
        "python.import",
        "critical",
        ["ImportError:"],
        "Falló un import.",
        "Versión incompatible o símbolo ausente.",
        ["ImportError:"],
        ["Lee el símbolo faltante.", "Alinea versiones de dependencias."],
        title="ImportError",
        tags=["python"],
    ),
    rule(
        "python.attribute",
        "critical",
        ["AttributeError:"],
        "Se accedió a un atributo inexistente.",
        "None inesperado o API cambiada.",
        ["AttributeError:"],
        ["Revisa el objeto en el frame.", "Valida None antes de usar."],
        title="AttributeError",
        tags=["python"],
    ),
    rule(
        "python.key",
        "warn",
        ["KeyError:"],
        "Clave ausente en dict.",
        "Payload incompleto o typo de key.",
        ["KeyError:"],
        ["Usa .get con default o valida schema.", "Revisa la key en el mensaje."],
        title="KeyError",
        tags=["python"],
    ),
    rule(
        "python.type",
        "critical",
        ["TypeError:"],
        "TypeError en runtime Python.",
        "Tipos incompatibles en una operación.",
        ["TypeError:"],
        ["Lee operandos del mensaje.", "Añade validación de tipos."],
        title="TypeError",
        tags=["python"],
    ),
    rule(
        "python.value",
        "warn",
        ["ValueError:"],
        "ValueError: valor inválido.",
        "Parseo o rango incorrecto.",
        ["ValueError:"],
        ["Valida inputs.", "Revisa conversiones int/str/date."],
        title="ValueError",
        tags=["python"],
    ),
    rule(
        "python.django",
        "warn",
        ["django."],
        "Error en stack Django.",
        "Vista, ORM o settings.",
        ["django."],
        ["Lee la excepción Django específica.", "Revisa settings y migraciones."],
        title="Django",
        tags=["django"],
    ),
    rule(
        "python.flask",
        "warn",
        ["werkzeug", "flask.app"],
        "Error en Flask/Werkzeug.",
        "Ruta, request o servidor.",
        ["werkzeug", "flask"],
        ["Revisa el handler de la ruta.", "Mira el request path en el log."],
        title="Flask",
        tags=["flask"],
    ),
    rule(
        "python.fastapi",
        "warn",
        ["fastapi", "uvicorn.error"],
        "Error en FastAPI/Uvicorn.",
        "Validación Pydantic o excepción en endpoint.",
        ["fastapi", "uvicorn"],
        ["Revisa el endpoint y el validation error.", "Confirma dependencies."],
        title="FastAPI/Uvicorn",
        tags=["fastapi"],
    ),
    rule(
        "python.sqlalchemy",
        "critical",
        ["sqlalchemy", "OperationalError", "IntegrityError"],
        "Error SQLAlchemy / integridad o conexión.",
        "BD caída, constraint o SQL inválido.",
        ["sqlalchemy", "OperationalError", "IntegrityError"],
        ["Lee el DBAPI error anidado.", "Verifica conexión y constraints."],
        title="SQLAlchemy",
        tags=["db"],
    ),
    rule(
        "python.psycopg",
        "critical",
        ["psycopg2", "psycopg"],
        "Error del driver PostgreSQL (psycopg).",
        "Auth, red o SQL.",
        ["psycopg2", "psycopg"],
        ["Verifica DSN y red al Postgres.", "Revisa SQL/estado de la BD."],
        title="psycopg",
        tags=["db"],
    ),
    rule(
        "python.permission",
        "warn",
        ["PermissionError:"],
        "Permiso denegado sobre un recurso de filesystem.",
        "UID del contenedor sin acceso al path.",
        ["PermissionError:"],
        ["Revisa volúmenes y user del pod.", "Ajusta permisos fuera de Faro."],
        title="PermissionError",
        tags=["fs"],
    ),
    rule(
        "python.timeout",
        "warn",
        ["TimeoutError", "timed out"],
        "Operación Python agotó el tiempo de espera.",
        "Red lenta o deadlock.",
        ["TimeoutError", "timed out"],
        ["Revisa timeouts de clientes.", "Mira dependencias lentas."],
        title="Timeout",
        tags=["network"],
    ),
    rule(
        "python.asyncio",
        "warn",
        ["Task exception was never retrieved"],
        "Problema con tareas asyncio.",
        "Task sin await/exception handler.",
        ["Task exception was never retrieved"],
        ["Asegura await de tasks.", "Añade exception handlers."],
        title="asyncio",
        tags=["python"],
    ),
    rule(
        "python.generic",
        "info",
        ["Error:", "ERROR"],
        "Error genérico en log Python.",
        "Prioriza Traceback/reglas específicas si existen.",
        ["Error:"],
        ["Busca Traceback arriba.", "Lee la excepción concreta."],
        title="Error genérico Python",
        tags=["ops"],
    ),
]


def write_pack(pid, name, rules):
    d = os.path.join(root, pid)
    os.makedirs(d, exist_ok=True)
    path = os.path.join(d, "default.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump({"id": pid, "displayName": name, "rules": rules}, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"{pid}: {len(rules)} rules -> {path}")


write_pack("springboot", "Spring Boot / JVM", spring)
write_pack("liquibase", "Liquibase", liquibase)
write_pack("nodejs", "Node.js", nodejs)
write_pack("react", "React", react)
write_pack("python", "Python", python)
